// Map of path segments / full paths to human-readable labels.
// Prefers full-path match, falls back to segment match, then title-cases.
export const breadcrumbLabels: Record<string, string> = {
  '/dashboard': 'Dashboard',
  '/pipeline': 'Pipeline',
  '/clients': 'Clients',
  '/agents': 'Agents',
  '/coaching': 'Coaching',
  '/tasks': 'Tasks',
  '/tickets': 'Tickets',
  '/commissions': 'Commissions',
  '/clawbacks': 'Clawbacks',
  '/leaderboards': 'Leaderboards',
  '/announcements': 'Announcements',
  '/knowledge': 'Knowledge',
  '/scripts': 'Scripts',
  '/settings': 'Settings',
  '/qa': 'Quality Assurance',
  '/qa/scorecards': 'Scorecards',
  '/qa/evaluate': 'Evaluate',
  '/qa/evaluations': 'Evaluations',
  '/qa/queue': 'Queue',
  '/rta': 'Real-Time Adherence',
  '/rta/agents': 'Agents',
  '/rta/breaks': 'Breaks',
  '/rta/infractions': 'Infractions',
  '/admin': 'Admin',
  '/admin/users': 'Users',
  '/admin/scripts': 'Scripts',
  '/admin/commissions': 'Commissions',
  '/admin/announcements': 'Announcements',
  '/admin/knowledge': 'Knowledge',
  '/admin/settings': 'Settings',
  // Shorthand fallbacks
  dashboard: 'Dashboard',
  pipeline: 'Pipeline',
  clients: 'Clients',
  agents: 'Agents',
  coaching: 'Coaching',
  tasks: 'Tasks',
  tickets: 'Tickets',
  commissions: 'Commissions',
  clawbacks: 'Clawbacks',
  leaderboards: 'Leaderboards',
  announcements: 'Announcements',
  knowledge: 'Knowledge',
  scripts: 'Scripts',
  settings: 'Settings',
  qa: 'QA',
  rta: 'RTA',
  admin: 'Admin',
}
